/** Datos de ejemplo Carchi para demostrar el portal productor y empresa. */

function id(suffix) {
  // UUIDs estables para demos (válidos para sync)
  return `00000000-0000-4000-8000-${String(suffix).padStart(12, '0')}`
}

const HOY = new Date().toISOString().slice(0, 10)
const hace = (dias) => {
  const d = new Date()
  d.setDate(d.getDate() - dias)
  return d.toISOString().slice(0, 10)
}

/**
 * Semilla offline del agricultor Dylan (parcelas, plantas, riego, métricas, circular, planes).
 */
export function buildProductorDemoSeed(auth = {}) {
  const productorId = auth.productor_id || id(1)
  const p1 = id(101)
  const p2 = id(102)
  const p3 = id(103)
  const pl = (n) => id(200 + n)

  const plantas = [
    {
      id: pl(1),
      parcela_id: p1,
      codigo: 'AND-ANGEL-01',
      fecha_siembra: '2024-03-12',
      tipo_propagacion: 'hijuelo',
      peso_hijuelo_kg: 2.1,
      tamano_roseta_inicial_cm: 9.5,
      edad_planta_madre_anios: 4,
      dias_cicatrizacion: 10,
      tratamiento_sanitario: true,
      metodo_desinfeccion: 'fuego',
      hijuelo_apto: true,
      estado: 'activa',
      ubicacion_lat: 0.6221,
      ubicacion_lng: -77.9372,
      notas: 'Siembra andina en zanjas · demo',
      synced_at: null,
    },
    {
      id: pl(2),
      parcela_id: p1,
      codigo: 'AND-ANGEL-02',
      fecha_siembra: '2024-03-12',
      tipo_propagacion: 'hijuelo',
      peso_hijuelo_kg: 1.8,
      tamano_roseta_inicial_cm: 8.8,
      edad_planta_madre_anios: 3.5,
      dias_cicatrizacion: 10,
      tratamiento_sanitario: true,
      metodo_desinfeccion: 'fuego',
      hijuelo_apto: true,
      estado: 'activa',
      ubicacion_lat: 0.6223,
      ubicacion_lng: -77.9368,
      notas: 'Hijuelo firme',
      synced_at: null,
    },
    {
      id: pl(3),
      parcela_id: p2,
      codigo: 'AND-LOMA-01',
      fecha_siembra: '2023-11-05',
      tipo_propagacion: 'hijuelo',
      peso_hijuelo_kg: 2.4,
      tamano_roseta_inicial_cm: 10.2,
      edad_planta_madre_anios: 5,
      dias_cicatrizacion: 11,
      tratamiento_sanitario: true,
      metodo_desinfeccion: 'fuego',
      hijuelo_apto: true,
      estado: 'activa',
      ubicacion_lat: 0.5982,
      ubicacion_lng: -77.9101,
      notas: 'Ladera anti-erosión',
      synced_at: null,
    },
    {
      id: pl(4),
      parcela_id: p2,
      codigo: 'AND-LOMA-02',
      fecha_siembra: '2023-11-05',
      tipo_propagacion: 'semilla',
      dias_cicatrizacion: 0,
      tratamiento_sanitario: false,
      metodo_desinfeccion: 'n/a',
      estado: 'activa',
      ubicacion_lat: 0.5984,
      ubicacion_lng: -77.9098,
      notas: 'Vivero · germinación baja ~5%',
      synced_at: null,
    },
    {
      id: pl(5),
      parcela_id: p3,
      codigo: 'MX-CHOTA-01',
      fecha_siembra: '2025-01-20',
      tipo_propagacion: 'hijuelo',
      peso_hijuelo_kg: 2.0,
      tamano_roseta_inicial_cm: 9.0,
      edad_planta_madre_anios: 4,
      dias_cicatrizacion: 10,
      tratamiento_sanitario: true,
      metodo_desinfeccion: 'fuego',
      hijuelo_apto: true,
      estado: 'activa',
      ubicacion_lat: 0.4852,
      ubicacion_lng: -78.0502,
      notas: 'Método mexicano · intercalado papa',
      synced_at: null,
    },
  ]

  const mediciones = [
    {
      id: id(301),
      planta_id: pl(1),
      fecha_medicion: hace(90),
      altura_roseta_cm: 28,
      diametro_roseta_cm: 34,
      numero_hojas: 16,
      estado_general: 'sana',
      tipo_carbono: 'verificado_in_situ',
      carbono_verificado: true,
      biomasa_kg: 3.32,
      carbono_acumulado_kg: 1.56,
      co2_equivalente_kg: 5.73,
      algoritmo_version: 'alometrico_v1',
      synced_at: null,
    },
    {
      id: id(302),
      planta_id: pl(1),
      fecha_medicion: hace(30),
      altura_roseta_cm: 36,
      diametro_roseta_cm: 42,
      numero_hojas: 20,
      estado_general: 'sana',
      tipo_carbono: 'verificado_in_situ',
      carbono_verificado: true,
      biomasa_kg: 4.2,
      carbono_acumulado_kg: 1.97,
      co2_equivalente_kg: 7.24,
      algoritmo_version: 'alometrico_v1',
      synced_at: null,
    },
    {
      id: id(303),
      planta_id: pl(3),
      fecha_medicion: hace(45),
      altura_roseta_cm: 48,
      diametro_roseta_cm: 55,
      numero_hojas: 24,
      estado_general: 'sana',
      tipo_carbono: 'verificado_in_situ',
      carbono_verificado: true,
      biomasa_kg: 5.28,
      carbono_acumulado_kg: 2.48,
      co2_equivalente_kg: 9.1,
      algoritmo_version: 'alometrico_v1',
      synced_at: null,
    },
    {
      id: id(304),
      planta_id: pl(5),
      fecha_medicion: hace(14),
      altura_roseta_cm: 22,
      diametro_roseta_cm: 26,
      numero_hojas: 14,
      estado_general: 'estresada',
      tipo_carbono: 'estimado',
      carbono_verificado: false,
      biomasa_kg: 2.78,
      carbono_acumulado_kg: 1.31,
      co2_equivalente_kg: 4.8,
      algoritmo_version: 'alometrico_v1',
      synced_at: null,
    },
  ]

  const bitacora = [
    {
      id: id(401),
      productor_id: productorId,
      parcela_id: p1,
      tipo: 'riego',
      fecha_programada: hace(5),
      estado: 'completada',
      gps_lat: 0.6221,
      gps_lng: -77.9372,
      datos: { estacion: 'primavera', estado_lote: 'sano' },
      notas: 'Riego normal · surcos altos',
      synced_at: null,
    },
    {
      id: id(402),
      productor_id: productorId,
      parcela_id: p1,
      tipo: 'monitoreo',
      fecha_programada: hace(5),
      estado: 'completada',
      datos: { estado_lote: 'sano' },
      notas: 'Estado del lote: sano',
      synced_at: null,
    },
    {
      id: id(403),
      productor_id: productorId,
      parcela_id: p2,
      tipo: 'riego',
      fecha_programada: hace(12),
      estado: 'completada',
      datos: { estacion: 'invierno' },
      notas: 'Riego mínimo invierno',
      synced_at: null,
    },
    {
      id: id(404),
      productor_id: productorId,
      parcela_id: p2,
      tipo: 'fertilizacion',
      fecha_programada: hace(40),
      estado: 'completada',
      datos: {},
      notas: 'Composta en zanjas',
      synced_at: null,
    },
    {
      id: id(405),
      productor_id: productorId,
      parcela_id: p3,
      tipo: 'scouting_visual',
      fecha_programada: hace(7),
      estado: 'completada',
      datos: { clasificacion: 'cochinilla' },
      notas: 'Puntos rojos en 2 pencas · tratado',
      synced_at: null,
    },
    {
      id: id(406),
      productor_id: productorId,
      parcela_id: p3,
      tipo: 'monitoreo',
      fecha_programada: hace(7),
      estado: 'completada',
      datos: { estado_lote: 'plaga' },
      notas: 'Estado: plaga controlada',
      synced_at: null,
    },
    {
      id: id(407),
      productor_id: productorId,
      parcela_id: p1,
      tipo: 'poda_sanitaria',
      fecha_programada: hace(20),
      estado: 'completada',
      datos: {},
      notas: 'Hojas secas eliminadas',
      synced_at: null,
    },
  ]

  const residuos = [
    {
      id: id(501),
      planta_id: pl(3),
      tipo_residuo: 'fibra_cabuya',
      destino_producto: 'canastas',
      cantidad_kg: 12.5,
      ingreso_adicional_usd: 106.25,
      created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
      synced_at: null,
    },
    {
      id: id(502),
      planta_id: pl(3),
      tipo_residuo: 'flores_kirillas',
      destino_producto: 'encurtidos',
      cantidad_kg: 3.2,
      ingreso_adicional_usd: 57.6,
      created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
      synced_at: null,
    },
    {
      id: id(503),
      planta_id: pl(1),
      tipo_residuo: 'hoja_para_abono',
      destino_producto: 'abono_compost',
      cantidad_kg: 40,
      ingreso_adicional_usd: 48,
      created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
      synced_at: null,
    },
    {
      id: id(504),
      planta_id: pl(5),
      tipo_residuo: 'chawarquero_madera',
      destino_producto: 'construccion_vigas',
      cantidad_kg: 8,
      ingreso_adicional_usd: 48,
      created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
      synced_at: null,
    },
  ]

  return {
    productor: {
      id: productorId,
      nombre: auth.nombre || 'Dylan · Agricultor',
      email: auth.email || 'dylan@pencolab.ec',
      comunidad: 'Pencos del Norte · El Ángel',
    },
    parcelas: [
      {
        id: p1,
        productor_id: productorId,
        nombre: 'Ladera El Ángel Norte',
        area_hectareas: 1.5,
        fecha_establecimiento: '2024-03-12',
        ph: 6.4,
        tipo_suelo: 'franco',
        permeabilidad: 'media',
        tipo_trazado: 'zanjas',
        tipo_planta: 'penco_andino',
        metas_expansion_ha: 20,
        ubicacion_lat: 0.6225,
        ubicacion_lng: -77.937,
        estado_lote: 'sano',
        ultimo_riego: hace(5),
        recomendacion_ph: 'pH en rango óptimo para Penco/Agave (6.0–7.0)',
        synced_at: null,
      },
      {
        id: p2,
        productor_id: productorId,
        nombre: 'Terrazas Miraflor',
        area_hectareas: 1.0,
        fecha_establecimiento: '2023-11-05',
        ph: 5.7,
        tipo_suelo: 'franco-arenoso',
        permeabilidad: 'alta',
        tipo_trazado: 'laderas',
        tipo_planta: 'penco_denso',
        metas_expansion_ha: 20,
        ubicacion_lat: 0.598,
        ubicacion_lng: -77.91,
        estado_lote: 'atencion',
        ultimo_riego: hace(12),
        recomendacion_ph: 'Suelo ácido: cal y composta',
        synced_at: null,
      },
      {
        id: p3,
        productor_id: productorId,
        nombre: 'Chota Sur · Papa intercalada',
        area_hectareas: 0.5,
        fecha_establecimiento: '2025-01-20',
        ph: 6.8,
        tipo_suelo: 'franco',
        permeabilidad: 'media',
        tipo_trazado: 'zanjas',
        tipo_planta: 'intercalado_papa',
        metas_expansion_ha: 20,
        ubicacion_lat: 0.485,
        ubicacion_lng: -78.05,
        estado_lote: 'plaga',
        ultimo_riego: hace(7),
        recomendacion_ph: 'pH en rango óptimo para Penco/Agave (6.0–7.0)',
        synced_at: null,
      },
    ],
    plantas,
    mediciones,
    bitacora,
    residuos,
    vivero_semillas: [
      {
        id: id(601),
        lote_semillas: 'LOTE-VIV-2025-08',
        fecha_siembra: '2025-08-01',
        cantidad_sembradas: 200,
        cantidad_germinadas: 11,
        tasa_germinacion_real: 5.5,
        synced_at: null,
      },
    ],
    planes_accion: [
      {
        id: id(701),
        productor_id: productorId,
        hectareas_planificadas: 3,
        cultivo_intercalado_elegido: 'papa',
        cultivo_intercalado_label: 'Papas del Carchi',
        fecha_inicio_plan: HOY,
        densidad_plantas_ha: 1000,
        plantas_totales: 3000,
        ingreso_penco_usd: 480000,
        ingreso_intercalado_6m_usd: 3600,
        co2_mitigado_ton: 15,
        estado: 'planificado',
        latitud_inicial: 0.6225,
        longitud_inicial: -77.937,
        created_at: new Date().toISOString(),
        synced_at: null,
        proyeccion_financiera: {
          ingreso_total_estimado_usd: 483600,
          ingreso_penco_madurez_usd: 480000,
          ingreso_corto_plazo_usd: 3600,
          plantas_totales: 3000,
        },
      },
      {
        id: id(702),
        productor_id: productorId,
        hectareas_planificadas: 5,
        cultivo_intercalado_elegido: 'quinoa',
        cultivo_intercalado_label: 'Quinoa',
        fecha_inicio_plan: hace(20),
        densidad_plantas_ha: 2222,
        plantas_totales: 11110,
        ingreso_penco_usd: 1777600,
        ingreso_intercalado_6m_usd: 4750,
        co2_mitigado_ton: 25,
        estado: 'activo_en_progreso',
        created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
        synced_at: null,
      },
    ],
  }
}

/** Residuos / planes de ejemplo (legacy). La empresa ya no escribe estos datos:
 *  lee la instantánea del productor (`pencolab_campo_snapshot_v1`). */
export function buildEmpresaDemoSeed() {
  return {
    residuos: [
      {
        id: id(801),
        planta_id: null,
        tipo_residuo: 'fibra_cabuya',
        destino_producto: 'alpargatas',
        cantidad_kg: 85,
        ingreso_adicional_usd: 722.5,
        created_at: new Date().toISOString(),
        synced_at: null,
      },
      {
        id: id(802),
        planta_id: null,
        tipo_residuo: 'flores_kirillas',
        destino_producto: 'encurtidos',
        cantidad_kg: 22,
        ingreso_adicional_usd: 396,
        created_at: new Date().toISOString(),
        synced_at: null,
      },
      {
        id: id(803),
        planta_id: null,
        tipo_residuo: 'chawarquero_madera',
        destino_producto: 'construccion_vigas',
        cantidad_kg: 60,
        ingreso_adicional_usd: 360,
        created_at: new Date().toISOString(),
        synced_at: null,
      },
      {
        id: id(804),
        planta_id: null,
        tipo_residuo: 'hoja_para_abono',
        destino_producto: 'abono_compost',
        cantidad_kg: 200,
        ingreso_adicional_usd: 240,
        created_at: new Date().toISOString(),
        synced_at: null,
      },
    ],
    planes_accion: [
      {
        id: id(901),
        hectareas_planificadas: 8,
        cultivo_intercalado_elegido: 'papa',
        estado: 'activo_en_progreso',
        plantas_totales: 8000,
        ingreso_penco_usd: 1280000,
      },
    ],
  }
}
