export const EMPRESA_DEMO = {
  dashboard: {
    productores: 12,
    parcelas: 28,
    plantas: 1840,
    carbono_estimado_kg: 18420,
    carbono_verificado_kg: 6100,
    co2_estimado_ton: 67.6,
    co2_verificado_ton: 22.4,
    co2_total_ton: 90.0,
    demo: true,
    serie_carbono: [
      { periodo: '2026-04', carbono_estimado_kg: 2200, carbono_verificado_kg: 400 },
      { periodo: '2026-05', carbono_estimado_kg: 3100, carbono_verificado_kg: 900 },
      { periodo: '2026-06', carbono_estimado_kg: 4200, carbono_verificado_kg: 1400 },
      { periodo: '2026-07', carbono_estimado_kg: 5800, carbono_verificado_kg: 2200 },
      { periodo: '2026-08', carbono_estimado_kg: 7200, carbono_verificado_kg: 3800 },
      { periodo: '2026-09', carbono_estimado_kg: 18420, carbono_verificado_kg: 6100 },
    ],
    comparativo: [
      { tipo: 'Estimado', carbono_kg: 18420, co2_ton: 67.6 },
      { tipo: 'Verificado', carbono_kg: 6100, co2_ton: 22.4 },
    ],
    parcelas_geo: [],
  },
  parcelas: [
    {
      id: 'd1',
      nombre: 'Finca El Ángel',
      productor: 'María Penco',
      lat: 0.6225,
      lng: -77.937,
      area_hectareas: 1.8,
      carbono_kg: 820,
      co2_kg: 3010,
      co2_kg_ha: 1672,
      ph: 6.4,
      linderos: [
        [0.6185, -77.941],
        [0.6185, -77.933],
        [0.6265, -77.933],
        [0.6265, -77.941],
      ],
    },
    {
      id: 'd2',
      nombre: 'Loma Miraflor',
      productor: 'José Agave',
      lat: 0.598,
      lng: -77.91,
      area_hectareas: 2.4,
      carbono_kg: 410,
      co2_kg: 1505,
      co2_kg_ha: 627,
      ph: 5.8,
      linderos: [
        [0.594, -77.914],
        [0.594, -77.906],
        [0.602, -77.906],
        [0.602, -77.914],
      ],
    },
    {
      id: 'd3',
      nombre: 'Valle Chota Sur',
      productor: 'Ana Ruiz',
      lat: 0.485,
      lng: -78.05,
      area_hectareas: 1.2,
      carbono_kg: 1290,
      co2_kg: 4734,
      co2_kg_ha: 3945,
      ph: 6.8,
      linderos: [
        [0.481, -78.054],
        [0.481, -78.046],
        [0.489, -78.046],
        [0.489, -78.054],
      ],
    },
    {
      id: 'd4',
      nombre: 'Costa Sur',
      productor: 'Luis Manta',
      lat: -2.18,
      lng: -80.0,
      area_hectareas: 3.1,
      carbono_kg: 560,
      co2_kg: 2055,
      co2_kg_ha: 663,
      ph: 7.1,
      linderos: [
        [-2.184, -80.004],
        [-2.184, -79.996],
        [-2.176, -79.996],
        [-2.176, -80.004],
      ],
    },
  ],
  crecimiento: {
    productores: [
      { id: 'p1', nombre: 'María Penco' },
      { id: 'p2', nombre: 'José Agave' },
    ],
    plantas: [
      { id: 'pl1', codigo: 'PN-DEMO-1', productor_id: 'p1' },
      { id: 'pl2', codigo: 'PN-DEMO-2', productor_id: 'p2' },
    ],
    series: {
      pl1: [
        { fecha: '2026-04-01', altura_roseta_cm: 18, diametro_roseta_cm: 22, numero_hojas: 12 },
        { fecha: '2026-05-15', altura_roseta_cm: 28, diametro_roseta_cm: 32, numero_hojas: 16 },
        { fecha: '2026-07-01', altura_roseta_cm: 40, diametro_roseta_cm: 45, numero_hojas: 22 },
        { fecha: '2026-09-01', altura_roseta_cm: 48, diametro_roseta_cm: 52, numero_hojas: 24 },
      ],
      pl2: [
        { fecha: '2026-05-01', altura_roseta_cm: 15, diametro_roseta_cm: 20, numero_hojas: 10 },
        { fecha: '2026-07-01', altura_roseta_cm: 26, diametro_roseta_cm: 30, numero_hojas: 15 },
        { fecha: '2026-09-01', altura_roseta_cm: 38, diametro_roseta_cm: 42, numero_hojas: 20 },
      ],
    },
  },
  alertas: [
    {
      id: 'a1',
      tipo: 'scouting_visual',
      fecha: '2026-09-01',
      notas:
        'En las pencas de abajo se ven puntos rojos y una capa blanca como algodón. Sospecha de cochinilla en parcela Ángel.',
      gps_lat: 0.6225,
      gps_lng: -77.937,
      clasificacion: 'cochinilla',
      productor: 'María Penco',
      parcela: 'Parcela Ángel · ladera norte',
      severidad: 'alta',
      plantas_afectadas: 12,
      estado: 'activa',
      foto: null,
      protocolo_mitigacion: null,
      datos: { clasificacion: 'cochinilla' },
    },
    {
      id: 'a2',
      tipo: 'fitosanitario',
      fecha: '2026-08-28',
      notas:
        'La base de la planta se siente blanda y huele mal. Posible pudrición por Erwinia. Hay riesgo de que se contagien las vecinas.',
      gps_lat: 0.598,
      gps_lng: -77.91,
      clasificacion: 'pudricion_erwinia',
      productor: 'José Agave',
      parcela: 'Parcela Loma · zanja 2',
      severidad: 'critica',
      plantas_afectadas: 3,
      estado: 'activa',
      foto: null,
      protocolo_mitigacion: null,
      datos: { clasificacion: 'pudricion_erwinia' },
    },
    {
      id: 'a3',
      tipo: 'scouting_visual',
      fecha: '2026-08-20',
      notas:
        'Orificios en el tallo y pencas mordidas. Señales de picudo del agave. Revisar hijuelos recién plantados.',
      gps_lat: 0.6102,
      gps_lng: -77.925,
      clasificacion: 'picudo_agave',
      productor: 'Rosa Quilo',
      parcela: 'Vivero · bandeja B',
      severidad: 'media',
      plantas_afectadas: 5,
      estado: 'activa',
      foto: null,
      protocolo_mitigacion: null,
      datos: { clasificacion: 'picudo_agave' },
    },
  ],
  eficiencia: {
    modelo: 'eficiencia_campo_mexico',
    total_plantas: 1840,
    plantas_certificadas: 1480,
    plantas_tradicionales: 360,
    lotes_certificados: 18,
    proyeccion_cosecha: [
      {
        hito: 'Año 5',
        edad_anios: 5,
        pinas_proyectadas: 1840,
        pinas_certificadas_vivas: 1766,
        pinas_tradicionales_vivas: 1288,
        descripcion: 'Primera ventana de extracción de piña / chawada temprana',
      },
      {
        hito: 'Año 8',
        edad_anios: 8,
        pinas_proyectadas: 1840,
        pinas_certificadas_vivas: 1766,
        pinas_tradicionales_vivas: 1288,
        descripcion: 'Pico productivo de corazones de penco',
      },
      {
        hito: 'Año 12',
        edad_anios: 12,
        pinas_proyectadas: 1840,
        pinas_certificadas_vivas: 1766,
        pinas_tradicionales_vivas: 1288,
        descripcion: 'Madurez plena · máxima extracción acumulada',
      },
    ],
    perdidas_fitosanitarias: [
      {
        modelo: 'Tradicional',
        mortalidad_pct: 30,
        supervivencia_pct: 70,
        plantas_base: 360,
        plantas_perdidas: 108,
        plantas_vivas: 252,
        detalle: 'Sin desinfección al fuego ni cicatrización de 10 días',
      },
      {
        modelo: 'Certificado México',
        mortalidad_pct: 4,
        supervivencia_pct: 96,
        plantas_base: 1480,
        plantas_perdidas: 59,
        plantas_vivas: 1421,
        detalle: 'Desinfección al fuego + cicatrización al sol 10 días',
      },
    ],
    roi: {
      hectareas: 1,
      eucalipto: {
        arboles: 1100,
        usd_por_arbol_12a: 20,
        ingreso_total_usd: 22000,
        densidad_ha: 1100,
        horizonte_anios: 12,
      },
      penco_certificado: {
        plantas: 1999,
        usd_por_planta: 160,
        ingreso_total_usd: 319840,
        densidad_ha: 2222,
        fuente: 'Venta garantizada de chawarmishky (aguamiel)',
      },
      multiplicador: 14.5,
      comparativo_grafico: [
        { cultivo: 'Eucalipto (12 a)', usd_por_unidad: 20, ingreso_ha_usd: 22000 },
        { cultivo: 'Penco certificado', usd_por_unidad: 160, ingreso_ha_usd: 319840 },
      ],
    },
  },
};

export const PROTOCOLO_COCHINILLA =
  'Limpiar las pencas afectadas con algodón y alcohol, o lavar con agua y jabón. Quitar hojas secas que sirven de puente a la plaga.'

/** Guía clara de alertas fitosanitarias (empresa + scouting). */
export const FITO_GUIA = {
  cochinilla: {
    id: 'cochinilla',
    nombre: 'Cochinilla',
    icon: 'cochinilla',
    color: '#b91c1c',
    bg: '#fef2f2',
    que_es: 'Insecto que chupa savia. Deja puntos rojos y una capa blanca como algodón en las pencas.',
    como_se_ve: [
      'Puntos rojos en pencas de abajo',
      'Polvo o algodón blanco pegado a la hoja',
      'Planta se ve débil si avanza mucho',
    ],
    riesgo: 'Puede bajar el vigor y abrir puerta a otras plagas si no se limpia a tiempo.',
    urgencia: 'Actuar en 24–48 h',
    pasos: [
      'Aislar o marcar las plantas afectadas',
      'Limpiar pencas con alcohol o agua + jabón',
      'Quitar solo hojas secas (poda sanitaria)',
      'Volver a revisar en 3–5 días',
    ],
  },
  pudricion_erwinia: {
    id: 'pudricion_erwinia',
    nombre: 'Pudrición blanda (Erwinia)',
    icon: 'erwinia',
    color: '#9a3412',
    bg: '#fff7ed',
    que_es: 'Bacteria que ablanda y pudre la base o el corazón del penco. Se nota por olor y tejido blando.',
    como_se_ve: [
      'Base o corazón blando al tacto',
      'Olor fuerte / desagradable',
      'Hojas que se caen o se ponen acuosas',
    ],
    riesgo: 'Se puede contagiar a plantas vecinas y matar el hijuelo rápido.',
    urgencia: 'Actuar hoy',
    pasos: [
      'No regar en exceso ni encharcar',
      'Retirar tejido podrido con herramienta limpia',
      'Desinfectar machete/cuchillo al fuego entre plantas',
      'Separar o marcar plantas enfermas y avisar al productor',
    ],
  },
  picudo_agave: {
    id: 'picudo_agave',
    nombre: 'Picudo del agave',
    icon: 'picudo',
    color: '#92400e',
    bg: '#fffbeb',
    que_es: 'Escarabajo que perfora el tallo y las pencas. Usa hojas secas como refugio.',
    como_se_ve: [
      'Agujeros en tallo o pencas',
      'Mordeduras o galerías internas',
      'Hojas secas acumuladas cerca de la planta',
    ],
    riesgo: 'Daña hijuelos y plantas jóvenes; las hojas secas facilitan su avance.',
    urgencia: 'Actuar en 2–3 días',
    pasos: [
      'Quitar hojas secas (poda sanitaria)',
      'Revisar hijuelos y vivero',
      'Marcar plantas con orificios',
      'Evitar humedad excesiva en la base',
    ],
  },
  default: {
    id: 'default',
    nombre: 'Alerta de campo',
    icon: 'alerta',
    color: '#b45309',
    bg: '#fffbeb',
    que_es: 'Reporte fitosanitario enviado desde el scouting del productor.',
    como_se_ve: ['Revisar notas y foto del reporte', 'Confirmar en campo si es posible'],
    riesgo: 'Depende del caso; conviene validar en sitio.',
    urgencia: 'Revisar pronto',
    pasos: [
      'Leer la nota del productor',
      'Ubicar el GPS o la parcela',
      'Confirmar el problema en campo',
      'Aplicar el protocolo que corresponda',
    ],
  },
}

export function guiaFitoDe(clasificacion) {
  const key = String(clasificacion || '')
    .toLowerCase()
    .trim()
  if (FITO_GUIA[key]) return FITO_GUIA[key]
  if (key.includes('cochinilla')) return FITO_GUIA.cochinilla
  if (key.includes('erwinia') || key.includes('pudric')) return FITO_GUIA.pudricion_erwinia
  if (key.includes('picudo')) return FITO_GUIA.picudo_agave
  return FITO_GUIA.default
}
